# Generated by Django 5.1.7 on 2025-03-16 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_caption', models.TextField(blank=True)),
                ('normal_caption', models.TextField(blank=True)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('query_result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_max', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='blog.imageanalysis')),
            ],
        ),
    ]
